name: sqflite_crud
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-134.0.dev

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.1.2
  path: ^1.8.0
  sqflite: ^2.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
